name: TypeScript Fixes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  fix-typescript-issues:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
    
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run TypeScript compiler and capture errors
      run: |
        npx tsc --noEmit > tsc_output.txt 2>&1 || true
        echo "TypeScript compiler output:"
        cat tsc_output.txt
    
    - name: Attempt to fix compiler issues and add imports
      run: |
        echo "Running ts-prune..."
        npx ts-prune || echo "ts-prune completed with issues"
        
        echo "Running ESLint fix..."
        npx eslint . --ext .ts,.tsx --fix || echo "ESLint fix completed with issues"
    
    - name: Check for changes
      id: git-check
      run: |
        git diff --exit-code || echo "::set-output name=changes::true"
    
    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        commit-message: 'fix: Attempted TypeScript fixes'
        title: 'Attempted TypeScript Fixes'
        body: |
          This PR contains attempted fixes for TypeScript issues.
          Some errors may persist and require manual intervention.
          Please review the changes carefully and make any necessary adjustments before merging.
          
          TypeScript compiler output is available in the workflow logs.
        branch: automated-typescript-fixes
        base: main
    
    - name: Upload TypeScript compiler output
      uses: actions/upload-artifact@v2
      with:
        name: tsc-output
        path: tsc_output.txt
